# @package model
type: DiffusionModel

diffSchedule: linear
diffSteps: 20
inferenceSamplingMode: ddpm
inferenceConditioningIntegration: clean
diffCondIntegration: clean
checkpoint: ""
load_betas: false
