# @package model
type: DiffusionModel

diffSchedule: linear
diffSteps: 20
inferenceSamplingMode: ddpm
inferenceConditioningIntegration: clean
diffCondIntegration: clean
checkpoint: ""
sigma_min: null
sigma_max: null
schedule_path: null