# @package _global_
defaults:
  - override /model: acdm

data:
  dataset_name: TransonicFlow
  data_path: /mnt/SSD2/constantin/autoreg-pde-diffusion/data
  resolution: 64
  frames_per_step: 2
  traj_length: 64
  frames_per_time_step: 1
  limit_trajectories_train: -1
  limit_trajectories_val: -1
  batch_size: 64
  val_batch_size: 64

model:
  dimension: 2
  dataSize: [128, 64]
  condChannels: 5
  dataChannels: 5
  padding_mode: same


loss:
  eval_traj_metrics: [mse]
  primary_metric: mse

wandb:
  project: TransonicFlow
